# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170829_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
