# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170914_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
